extends:
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - react
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  comma-dangle:
    - error
    - always-multiline
