language: elixir
elixir:
  - 1.3.4
env:
  - TRAVIS_NODE_VERSION="7.0.0"
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn install
cache:
  directories:
  - $HOME/.yarn-cache
script:
  - mix test
  - npm test
