version: '2'

services:

  client:
    build: client/
    volumes:
      - static_assets:/usr/src/app/build
    command: npm start

  db:
    image: postgres

  server:
    build: server/
    depends_on:
      - db
    links:
      - db
    command: mix phoenix.server

  nginx:
    ports:
      - '3000:80'
    build: nginx/
    volumes:
      - static_assets:/usr/share/nginx/static_assets
    links:
      - server
    depends_on:
      - server
      - client

volumes:
  static_assets:
